
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import 'swiper/css';
import '../../assets/css/icofont.min.css'
import '../../assets/css/animate.css';
import '../../assets/css/style.min.css';
import AuthProvide from "./AuthProvide";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopCart – Authentication ",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body  className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <AuthProvide>
        {children}
        </AuthProvide>
      </body>
    </html>
  );
}
